### ISSUE TITLE
Consider merging with Github Hall of Fame

### ISSUE THREAD

**Issue by stevemoser** [nikolas/github-drama#15]
https://github.com/halls-of-fame/github

**Comment by nikolas** [comment]
I have lots of problems with the Github Hall of Fame.

* Why does their list of links have a Gemfile? a config.yml? Custom CSS? These are all unnecessary. I like making things as simple as possible, which is why I've put everything in the README, so it all shows up on the repo page.
* Their mission statement begins, "Open source sometimes is awesome." I have lots of problems with this statement. First of all, I don't like it when people call it "Open Source software", and even worse, just "Open Source". It makes it sound like a niche, like a part of a larger world of software, a small portion of which happens to be "open source". As a maintainer and contributor to the GNU project, using the term "open source" also ignores the movement which I more closely identify with, which is "free software". Second of all, I hate the word "awesome", unless you're using it in a joking way, or you're skateboarding or surfing. Tech yuppies in San Francisco using the word "awesome" is really dumb.
* The Hall of Fame includes threads like this: https://github.com/rails/rails/issues/16731 which aren't "dramatic" at all, unless you count making me want to vomit as "dramatic".

So, I think we are just two different projects, with two very different goals, which is fine.

**Comment by jomo** [comment]
> Why does their list of links have a Gemfile? a config.yml? Custom CSS? These are all unnecessary.

Because it produces [this GitHub page](https://halls-of-fame.github.io/github/).

Not all projects on GitHub are free/libre, and some of it is not even software, but it's definitely open source. *[Is this how discussions end up on the drama list?]*

Just my 2 cents, it's probably better to keep the projects separated.

**Comment by nikolas** [comment]
> Because it produces this GitHub page.

I see they're using jekyll, I just meant that I thought a plain text file is sufficient for a list of this size.

> Not all projects on GitHub are free/libre, and some of it is not even software, but it's definitely open source.

Yeah true.. but there is lots of software that doesn't have a license on github, which [isn't open source](http://choosealicense.com/no-license/), right? But anyways, that's not so important. Basically the mission statements of the two projects are different.

> [Is this how discussions end up on the drama list?]

We are heading there! It would be interesting if one of these threads ended up on its own list.

**Comment by nikolas** [comment]
I apologize for getting so worked up in this thread. I don't want to end up in github-drama.

**Comment by stevemoser** [comment]
> [Is this how discussions end up on the drama list?]

Haha, classic. Yes, it definitely seems like the repos should stay separate.

**Comment by upintheairsheep** [comment]
> I apologize for getting so worked up in this thread. I don't want to end up in github-drama.

This is the closest issue in github-drama to become github-drama itself

**Comment by InCogNiTo124** [comment]
Meta
